name = "arduino-otopark-api"
main = "server.js"
compatibility_date = "2024-03-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "arduino-otopark-db"
database_id = "531145a0-cf14-41bd-a1af-60dfc8b7ce0f"

# Workers Logs ayarları
[workers_dev]
enabled = true

[logs]
enabled = true
head_sampling_rate = 1.0
include_invocation_logs = true