name = "arduino-otopark-api"
main = "server.js"
compatibility_date = "2024-03-02"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "arduino-otopark-db"
database_id = "531145a0-cf14-41bd-a1af-60dfc8b7ce0f"

# Loglama ayarları
[triggers]
crons = []

[logs]
workers_dev = true # Worker loglarını etkinleştir
sampling_rate = 1.0 # Tüm istekleri logla